Repository ducami-org/ducademi-server, pull requests merged in 2024-04, with the labels that each got.

#9 Feat :: 기본 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/📧-기본-이슈-템플릿.md
Labels: 📄：문서

#29 게시글 기본 CRUD 기능 구현
  .github/ISSUE_TEMPLATE/📧-기본-이슈-템플릿.md
  build.gradle
  src/main/java/ducami/org/ducademi/DucademiApplication.java
  src/main/java/ducami/org/ducademi/domain/board/controller/BoardController.java
  src/main/java/ducami/org/ducademi/domain/board/dto/BoardResponseDTO.java
  src/main/java/ducami/org/ducademi/domain/board/dto/CreateBoardRequestDTO.java
  src/main/java/ducami/org/ducademi/domain/board/dto/GetBoardsResponseDTO.java
  src/main/java/ducami/org/ducademi/domain/board/entity/BoardEntity.java
  src/main/java/ducami/org/ducademi/domain/board/entity/FileEntity.java
  src/main/java/ducami/org/ducademi/domain/board/repository/BoardRepository.java
  src/main/java/ducami/org/ducademi/domain/board/repository/FileRepository.java
  src/main/java/ducami/org/ducademi/domain/board/service/BoardService.java
  src/main/java/ducami/org/ducademi/domain/lecture/domain/Lecture.java
  src/main/java/ducami/org/ducademi/domain/lecture/domain/enums/LectureType.java
  src/main/java/ducami/org/ducademi/global/entity/BaseTimeEntity.java
  src/main/java/ducami/org/ducademi/global/exception/CustomErrorCode.java
Labels: 🐳：새로운, 📞：도움 !!

#53 생명 확인용 라우트 생성 & 멤버 CORS
  .github/workflows/coolify.yml
  .gitignore
  Dockerfile
  src/main/java/ducami/org/ducademi/domain/member/controller/MemberController.java
  src/main/java/ducami/org/ducademi/domain/test/TestController.java
  src/main/resources/application-jwt.yml
  src/main/resources/application-mysql.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: 🐳：새로운
